package com.evatool.impact.service.impl.rest;

import com.evatool.impact.common.dto.ImpactDto;
import com.evatool.impact.service.api.rest.ImpactRestService;

public class ImpactRestServiceImpl implements ImpactRestService {

    @Override
    public void createImpact(ImpactDto impact) {
        // TODO [tzaika] autogenerated
    }
}
