package com.evatool.impact.application.service;

import com.evatool.impact.application.dto.ImpactDto;

public class ImpactServiceImpl implements ImpactService {

    @Override
    public void createImpact(ImpactDto impactDto) {
        // TODO [tzaika] autogenerated
    }
}
